# sidebar:
#   logo:
#     avatar: "[https://cdn.jsdelivr.net/gh/booiris-cdn/img/warlord-helmet.svg](/)"
#   menu:
#     post: "[Blog](/)"
#     wiki: "[Doc](/wiki/)"
#     # notes: "[Notes](/notes/)"
#     game: "[Game](/game/)"
#     about: "[About](/about/)"
#     pic: "[Picture](/pic)"
#   widget_layout:
#     index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
#     page: [welcome, toc] # for pages using 'layout:page'
#     post: [toc, repo_info] # for pages using 'layout:post'
#     wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
#   widgets:
#     home: search, welcome, recent # for home

menubar:
  columns: 4 # 一行多少个
  items:
    - id: post
      title: Blog
      url: /
    - id: wiki
      title: Doc
      url: /wiki/
    - id: game
      title: Game
      url: /game
    - id: Picture
      title: Pic
      url: /pic

site_tree:
  # -- 列表类页面 -- #
  # 主页配置
  home:
    leftbar: welcome, recent
    rightbar: tagcloud, memos
  # 博客列表页配置
  # index_blog:
  #   base_dir: blog # 只影响自动生成的页面路径
  #   menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
  #   leftbar: welcome, recent # for categories/tags/archives
  #   rightbar:
  #   nav_tabs:  # 近期发布 分类 标签 专栏 归档 and ...
  #     # '朋友文章': /friends/rss/
  # # 博客专栏列表页配置
  # index_topic:
  #   base_dir: topic # 只影响自动生成的页面路径
  #   menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: welcome, recent # for wiki
    rightbar: tagcloud, memos
    # nav_tabs:
  #     # 'more': https://github.com/xaoxuu

  Picture:
    base_dir: /pic
    menu_id: Picture
    leftbar: welcome
    rightbar: memos

  # # -- 内容类页面 -- #
  # # 博客文章内页配置
  # post:
  #   menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
  #   leftbar: related, recent # for pages using 'layout:post'
  #   rightbar: ghrepo, toc
  # # 博客专栏文章内页配置
  # topic:
  #   menu_id: post
  # 文档内页配置
  # wiki:
  #   menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
  #   leftbar: tree, related, recent # for wiki
  #   rightbar: ghrepo, toc
  # 笔记本列表页配置
  # notebooks:
  #   base_dir: notebooks # 笔记本列表页的路径。以及未指定 base_dir 的笔记本的路径前缀。
  #   menu_id: notebooks # 笔记本列表页高亮的主导航栏菜单按钮。
  #   # 笔记本列表页的左侧栏和右侧栏。
  #   leftbar: recent # recent within all notebooks
  #   rightbar: null
  # # 笔记列表页配置
  # notes:
  #   # 笔记列表页和笔记页高亮的主导航栏菜单按钮。
  #   # 可以在笔记本 yaml 的 menu_id 字段中覆盖此参数。
  #   # 可以在笔记的 front-matter/menu_id 中覆盖此参数。
  #   menu_id: notebooks
  #   # 笔记列表页的左侧栏和右侧栏。可以在笔记本 yaml 的 leftbar 和 rightbar 字段中覆盖此参数。
  #   leftbar: tagtree, recent # recent of current notebook
  #   rightbar: null
  # # 笔记页配置
  # note:
  #   # 笔记页的左侧栏和右侧栏
  #   # 可以在笔记本 yaml 的 note_leftbar 和 note_rightbar 字段中覆盖此参数。
  #   # 可以在笔记的 front-matter/leftbar 和 rightbar 字段中覆盖此参数。
  #   leftbar: tagtree, recent # recent of current notebook
  #   rightbar: toc
  # # 作者信息配置
  # author:
  #   base_dir: author # 只影响自动生成的页面路径
  #   menu_id: post
  #   leftbar: recent, timeline
  #   rightbar: timeline
  # # 错误页配置
  # error_page:
  #   menu_id: post
  #   '404': '/404.html'
  #   leftbar: recent, timeline
  #   rightbar: timeline
  # # 其它自定义页面配置 layout: page
  # page:
  #   leftbar: recent
  #   rightbar: toc

logo:
  avatar: "https://cdn.jsdelivr.net/gh/booiris-cdn/img/warlord-helmet.svg" # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  # title: '[{config.title}](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'

article:
  auto_excerpt: 0
  license:
  related_posts:
    enable: false
    title: related article
  # share: [wechat, email, link]

footer:
  social:
    github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/booiris
    mail:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/a1b00e20f425d.svg"/>'
      url: mailto:booiris02@gmail.com
    steam:
      icon: '<img src="https://cdn.jsdelivr.net/gh/booiris-cdn/img/steam_47012.png"/>'
      url: https://steamcommunity.com/profiles/76561198081152126/
    screep:
      icon: '<img src="https://cdn.jsdelivr.net/gh/booiris-cdn/img/screep.png"/>'
      url: https://screeps.com/a/#!/profile/booiris
    rss:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rss" viewBox="0 0 16 16"> <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/> <path d="M5.5 12a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-3-8.5a1 1 0 0 1 1-1c5.523 0 10 4.477 10 10a1 1 0 1 1-2 0 8 8 0 0 0-8-8 1 1 0 0 1-1-1zm0 4a1 1 0 0 1 1-1 6 6 0 0 1 6 6 1 1 0 1 1-2 0 4 4 0 0 0-4-4 1 1 0 0 1-1-1z"/> </svg>'
      url: https://booiris.space/feed.xml

  # sitemap:
  #   "blog":
  #     - "[recent](/)"
  #     - "[categories](/categories)"
  #     - "[tags](/tags)"
  #     - "[archives](/archives)"
  #   "wiki":
  #     - "[main](/wiki)"
  #     - "[leetcode](/wiki/leetcode)"
  #     - "[redis](/wiki/redis)"
  #     - "[rust_code](/wiki/rust_code)"
  # license: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  # source: #'[GitHub](https://github.com/xaoxuu/hexo-theme-stellar)'
  # more: # string or array (support markdown)
  # content: | # 支持 Markdown 格式
  #   本站由 [@booiris](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
  #   本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。

copycode:
  enable: true
  js: /js/plugins/copycode.js
  default_text: "Copy" # 按钮显示文字
  success_text: "Copied" # 复制成功信息

style:
  # font-size:
  #   root: 16px
  #   body: .9375rem # 15px
  #   code: 85% # 14px
  #   codeblock: 0.8125rem # 13px
  font-family:
    logo: 'LXGW WenKai",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    # code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    # codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  # codeblock:
  #   highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css
  leftbar:
    background: var(--block)
    background-image:
    blur-px:
    blur-bg:

comments:
  service: beaudar
  beaudar:
    repo: booiris/comment
    branch: master
  comment_title: "🦻🦻🦻🦻🦻🦻🦻🦻"

data_services:
  memos:
    js: /js/memos.js
