sidebar:
  logo:
    avatar: '[https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg](/)' 
  menu:
    post: '[btn.blog](/)'

article:
  auto_excerpt: 0
  license:

plugins:
  mathjax:
    enable: false
    # cdn: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css