# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Booiris
subtitle: 'English by default🤖'
description: 'Hello world!'
favicon: /src/icon-32x32.ico
# avatar: /src/icon-32x32.ico
# favicon:
#   small: /src/icon-32x32.ico
#   #medium: /images/favicon-32x32-next.png
#   medium: /src/icon-32x32.ico
#   apple_touch_icon: /src/icon-32x32.ico
#   safari_pinned_tab: /src/icon-32x32.ico
#   android_manifest: /src/icon-32x32.ico
keywords:
author: booiris
language:
  - en
  - zh-CN

# timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://booiris.space
permalink: pages/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# highlight:
#   enable: true
#   line_number: false
#   auto_detect: false
#   tab_replace: '    '
#   wrap: false
#   hljs: true

# prismjs:
#   enable: false
#   preprocess: true
#   line_number: true
#   tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -updated

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'




# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar



# theme_config:
#   colorscheme: white
#   nav:
#     home: /
#     # about: /about/
#     tags: /tags/
#     categories: /categories/
#     articles: /archives/
#     # projects: https://github.com/booiris/
#     search: /search/
#     # LINK_NAME: URL
#   social_links:
#     github: https://github.com/booiris/
#     # twitter: your-twitter-url
#     mail: mailto:booiris02@gmail.com
#   mathjax:
#     enable: true
#     cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   icp: 
#     enabled: false
#   tongji:
#     enabled: false
#   cdn:
#     enabled: false
#   posts_overview:
#     show_all_posts: false
#     post_count: 10
#     sort_updated: true

# theme_config:
#   heti:
#     enable: true
#     css: https://unpkg.com/heti/umd/heti.min.css
#     js: https://unpkg.com/heti/umd/heti-addon.min.js

# npm i hexo-renderer-markdown-it-plus
# Markdown-it config
# markdown:
#   render:
#     html: true
#     xhtmlOut: false
#     breaks: true
#     linkify: true
#     typographer: true
#     quotes: '“”‘’'
#   plugins:
#     - markdown-it-abbr
#     - markdown-it-footnote
#     - markdown-it-ins
#     - markdown-it-sub
#     - markdown-it-sup
#   anchors:
#     level: 2
#     collisionSuffix: 'v'
#     permalink: true
#     permalinkClass: header-anchor
#     permalinkSymbol: ¶

# inject:
#   head:
#     - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
#     - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
#     # - <script defer src="src/auto-render.min.js"> </script>

# npm i hexo-renderer-markdown-it-plus
# markdown_it_plus:
#     highlight: true
#     html: true
#     xhtmlOut: true
#     breaks: true
#     langPrefix:
#     linkify: true
#     typographer:
#     quotes: “”‘’
#     plugins:
#         - plugin:
#             name: markdown-it-mark
#             enable: false
  # script:
inject:
  head:
    # - <link rel="preconnect" href="https://s1.hdslb.com/" />
    # - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="all" onload="this.media='all'" />
    - <link rel="icon" type="32x32" href="https://cdn.jsdelivr.net/gh/booiris-cdn/img/icon-32x32.ico">
    # - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
    # - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
    # - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>
    # - <link rel="stylesheet" href="https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.5.0/build/styles/atom-one-dark.min.css">
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@callmebill/lxgw-wenkai-web@latest/style.css" />


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: git@github.com:booiris/booiris.github.io.git
  branch: master

wiki_dir: wiki

sitemap:
  path: 
    - sitemap.xml
    # - sitemap.txt
  # template: ./sitemap_template.xml
  # template_txt: ./sitemap_template.txt
  rel: false
  tags: true
  categories: true

feed:
  enable: true
  type: atom
  path: feed.xml
  limit: 20
  # hub: https://pubsubhubbub.appspot.com
  # content: true
  order_by: -date
  icon: /src/icon-32x32.ico
  autodiscovery: true
  # template: ./source/uploads/atom_template.xml