sidebar:
  logo:
    avatar: '[https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg](/)' 
  menu:
    post: '[btn.blog](/)'

article:
  auto_excerpt: 0
  license:

plugins:
  mathjax:
    enable: true
    cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML