
# sidebar:
#   # logo:
#   #   title: '[<img no-lazy height="32px" src="xxx"/>](/)'
#   menu:z
#     post: '[btn.blog](/)'
#     # wiki: '[btn.wiki](/wiki/)'
#     notes: '[笔记](/notes/)'
#     # more: '[更多](/more/)'

article:
  auto_excerpt: 0
  license:

plugins:
  mathjax:
    enable: true
    cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML