name: HEXO_DEPLOY

on:
  push:
    branches:
      - source

env:
  POST_ASSET_IMAGE_CDN: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: xaoxuu/hexo-theme-stellar
          ref: master
          path: themes/stellar

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_SECRET }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "954520770@qq.com"
          git config --global user.name "booiris"
          npm install hexo-cli -g
          npm install
          npm uninstall hexo-math
          npm uninstall hexo-renderer-marked --save
          npm install hexo-renderer-kramed --save
          npm install hexo-generator-search --save
      - name: Hexo deploy
        run: |
          hexo clean
          hexo d